services:
  - type: web
    name: calorie-predictor-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    environment:
      pythonVersion: 3.10
